FROM python:3.10-busterAdd commentMore actions
WORKDIR /app

COPY requirements-freeze.txt .

RUN pip install --no-cache-dir -r requirements-freeze.txt

COPY . .
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
